FROM alpine:edge
ENV HOME=/tmp/quark-builder
RUN apk add 						\
	bash						\
	bison						\
	bpftool						\
	cjson						\
	cjson-dev					\
	clang						\
	gcc						\
	go						\
	libbpf						\
	libbpf-dev					\
	libbsd-dev					\
	linux-headers					\
	m4                                              \
	make						\
	musl-fts					\
	musl-fts-dev
