FROM alpine:3.22
ENV HOME=/tmp/quark-builder
RUN apk add 						\
	bash						\
	bison						\
	clang						\
	bpftool						\
	gcc						\
	go						\
	libbsd						\
	libbsd-dev					\
	make						\
	musl-fts					\
	musl-fts-dev					\
	m4
