.Dd $Mdocdate$
.Dt QUARK_QUEUE_CLOSE 3
.Os
.Sh NAME
.Nm quark_queue_close
.Nd closes a
.Vt quark_queue
.Sh SYNOPSIS
.In quark.h
.Ft int
.Fn quark_queue_close "struct quark_queue *qq"
.Sh DESCRIPTION
.Nm
closes the
.Vt quark_queue
pointed to by
.Fa qq ,
which must have been previously opened with
.Xr quark_queue_open 3 .
.Sh RETURN VALUES
Zero on success, -1 otherwise and
.Va errno
is set.
.Sh SEE ALSO
.Xr quark_event_dump 3 ,
.Xr quark_process_lookup 3 ,
.Xr quark_queue_block 3 ,
.Xr quark_queue_default_attr 3 ,
.Xr quark_queue_get_epollfd 3 ,
.Xr quark_queue_get_event 3 ,
.Xr quark_queue_get_stats 3 ,
.Xr quark_queue_open 3 ,
.Xr quark 7 ,
.Xr quark-btf 8 ,
.Xr quark-mon 8 ,
.Xr quark-test 8
