.Dd $Mdocdate$
.Dt QUARK_INIT 3
.Os
.Sh NAME
.Nm quark_init
.Nd initialize
.Nm quark
.Sh SYNOPSIS
.In quark.h
.Ft int
.Fn quark_init void
.Sh DESCRIPTION
.Fn quark_init
initializes the library global state, it should be called only once,
the process must be able to create kprobes as well as read
.Pa /sys/kernel/btf/vmlinux .
.Fn quark_close 3
cleans up all the state allocated by
.Fn quark_init 3 .
The following roughly summarizes what this function does:
.Bl -bullet
.It
Basic host attributes discovery, HZ and offsets
.It
BTF offsets
.It
Kprobe installation
.El
.Sh RETURN VALUES
Zero on success, -1 otherwise and
.Va errno
is set.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er EPERM
Probably due to not having permission to write to
.Fa tracefs .
.El
.Pp
Other values of
.Va errno
are possible.
.Sh SEE ALSO
.Xr quark_close 3 ,
.Xr quark_event_dump 3 ,
.Xr quark_event_lookup 3 ,
.Xr quark_queue_block 3 ,
.Xr quark_queue_close 3 ,
.Xr quark_queue_get_events 3 ,
.Xr quark_queue_get_fds 3 ,
.Xr quark 7 ,
.Xr quark-btf 8 ,
.Xr quark-mon 8
