steps:
  - label: "build amd64 in docker"
    key: make_docker
    command: "make docker"
    artifact_paths:
      - "initramfs.gz"
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2

  - label: "build amd64 in a centos7 container"
    key: make_centos7
    command: "make centos7"
    artifact_paths:
      - "quark-test"
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2

  - label: "build arm64 cross-compiled in docker"
    key: make_docker_cross_arm64
    command: "make docker-cross-arm64"
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2

  - label: "quark-test"
    key: test
    command: "./.buildkite/runtest.sh"
    depends_on:
      - make_centos7
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 32"
    key: test_fedora_32
    command: "./.buildkite/runtest_fedora.sh 32"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 33"
    key: test_fedora_33
    command: "./.buildkite/runtest_fedora.sh 33"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 34"
    key: test_fedora_34
    command: "./.buildkite/runtest_fedora.sh 34"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 35"
    key: test_fedora_35
    command: "./.buildkite/runtest_fedora.sh 35"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 36"
    key: test_fedora_36
    command: "./.buildkite/runtest_fedora.sh 36"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 37"
    key: test_fedora_37
    command: "./.buildkite/runtest_fedora.sh 37"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 38"
    key: test_fedora_38
    command: "./.buildkite/runtest_fedora.sh 38"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 39"
    key: test_fedora_39
    command: "./.buildkite/runtest_fedora.sh 39"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 40"
    key: test_fedora_40
    command: "./.buildkite/runtest_fedora.sh 40"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true

  - label: "quark-test on fedora 41"
    key: test_fedora_41
    command: "./.buildkite/runtest_fedora.sh 41"
    depends_on:
      - make_docker
    agents:
      image: family/core-ubuntu-2204
      provider: gcp
      machineType: n2-standard-2
      enableNestedVirtualization: true
